### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by cgzhan** [IronmanJay/BackgroundManagementSystemBasedOnSpringBootAndVue#2]
你好，技术大牛，你的这个项目的sql文件能提供一个吗，我想学习一下

**Comment by IronmanJay** [comment]
IronmanJay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IronmanJay/BackgroundManagementSystemBasedOnSpringBootAndVue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 下午5:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[IronmanJay/BackgroundManagementSystemBasedOnSpringBootAndVue] 技术咨询 (Issue #2)





 
你好，技术大牛，你的这个项目的sql文件能提供一个吗，我想学习一下

**Comment by IronmanJay** [comment]
可参考我的系列博客，其中介绍的非常详细：https://blog.csdn.net/IronmanJay/article/details/125723755
